
services:
  db:
    image: postgres
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Sergiu12
    networks:
      - app_net
    ports:
      - 5432:5432
    volumes:
      - /custom/newmount:/var/lib/postgresql/data
  backend:
    build: .
    container_name: testapp_con
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Sergiu12
    links:
      - db
    restart: always
    networks:
      - app_net

networks:
  app_net:
    external: true